feat: frontpage/data-hunter sync
Informasjonsforvaltning/fdk-frontend pull request #153
Opened 2024-08-08 09:50 UTC by Lillebo

2024-08-14 06:03 UTC, NilsOveTen approved these changes

2024-08-14 08:20 UTC, terjesyl requested changes
Det virker som indenteringen i noen av filene er satt til 8 spaces, eller 1 tab (med bredde lik 8 spaces). Følger det lint-reglene i repoet? Tror vi har pleid å ha 4 spaces i de andre prosjektene. Hva skjer om du kjører lint på hele prosjektet, blir det autoformatert riktig da?

2024-08-14 08:20 UTC, terjesyl commented on apps/frontpage/src/app/[lang]/layout.tsx
> +	description: ' data.norge.no er det offentlige nettstedet som gir oversikt over beskrivelser av datasett, begrep, api-er og informasjonsmodeller. Innholdet blir levert av ulike virksomheter, offentl
Kan/skal denne støtte flere språk?

2024-08-14 08:20 UTC, terjesyl commented on apps/frontpage/tsconfig.tsbuildinfo
Samme som over, skal denne filen versjoneres?

2024-08-14 08:20 UTC, terjesyl commented on libs/types/src/lib/common/index.ts
> +export type CatalogTypes = 'datasets' | 'apis' | 'terms' | 'information-models' | 'services-events' | 'ai';
`\n` legge til newline

2024-08-14 08:20 UTC, terjesyl commented on libs/ui/src/lib/catalog-symbol/catalog-symbol.stories.tsx
> +};
`\n`

2024-08-14 08:20 UTC, terjesyl commented on libs/ui/src/lib/catalogs-menu/catalogs-menu.stories.tsx
> +};
`\n`

2024-08-14 08:20 UTC, terjesyl commented on libs/ui/src/lib/footer/footer.stories.tsx
> +};
`\n`

2024-08-14 08:20 UTC, terjesyl commented on libs/ui/src/lib/header/header.stories.tsx
> +};
`\n`

2024-08-14 08:20 UTC, terjesyl commented on libs/ui/src/lib/language-switcher/language-switcher.stories.tsx
> +};
`\n`

2024-08-14 08:20 UTC, terjesyl commented on libs/ui/src/lib/logo/index.tsx
> +export { Logo, LogoLink };
`\n`

2024-08-14 08:20 UTC, terjesyl commented on libs/ui/src/lib/main-menu/data/index.ts
> +			title: dictionary.mainMenu.help.links.sharingData,
Døpe om til "Hvordan publisere beskrivelser"

2024-08-14 08:20 UTC, terjesyl commented on libs/ui/src/lib/main-menu/data/index.ts
>  		{
Legge til en entry "Hvordan dele data" som peker til Nasjonal verktøykasse for deling av data: https://www.digdir.no/datadeling/dele-data-med-andre/2252

![Screenshot 2024-08-14 at 10 18 40](https://github.com/user-attachments/assets/90a3c8d8-2d8d-411a-a907-7f7fb4f15b11)

2024-08-15 07:03 UTC, terjesyl commented on __mocks__/fileMock.js
Skal denne commites til versjonering/git?

2024-08-15 07:03 UTC, terjesyl commented on libs/dictionaries/src/lib/dictionaries/nb/common.json
>  				"description": "Kolleksjoner av strukturert data som kan lastes ned eller aksesseres via APIer"
"Samlinger av strukturert data som..."

2024-08-22 10:13 UTC, terjesyl approved these changes

2024-08-22 10:13 UTC, terjesyl commented on apps/frontpage/src/app/[lang]/components/frontpage-banner/components/scroll-button/index.tsx
> +export default ScrollButton;
newline: `\n`

2024-08-22 10:13 UTC, terjesyl commented on apps/frontpage/src/app/[lang]/components/frontpage-banner/components/scroll-button/scroll-button.module.scss
> +}
`\n`

2024-08-22 13:01 UTC, Lillebo commented on libs/ui/src/lib/main-menu/data/index.ts
> +			title: dictionary.mainMenu.help.links.sharingData,
Foreslår at vi venter litt med denne og den nedenfor inntil vi har tatt en runde på dokumentasjonen?

2024-08-26 14:01 UTC, jeffreiffers commented
Denne er allerede merget av https://github.com/Informasjonsforvaltning/fdk-frontend/pull/164

2024-08-26 14:01 UTC, closed without merging