Chore/pm/lint config
Informasjonsforvaltning/fdk-frontend pull request #2
Opened 2024-04-12 03:05 UTC by pooriamehregan

- Legger til Eslint og Prettier med anbefalte regler.
- Legger til pre-commit konfigurasjon for å kjøre linting, formatering og testene ved commit.
- Legger suggestions til .vscode som varsler utviklere om anbefalte vscode extensions for workspacet.

2024-04-15 11:27 UTC, NilsOveTen approved these changes

2024-04-15 12:03 UTC, terjesyl requested changes

2024-04-15 12:03 UTC, terjesyl commented on .vscode/settings.json
> +  "files.trimTrailingWhitespace": true // optional but recommended
Kommentarer er ikke gyldig i JSON, bør fjernes om denne filen skal sjekkes inn i versjoneringen:)

Og er det ok for alle at vi har felles vscode-settings for prosjektet? Bør være noe alle på teamet er med på.

2024-04-16 08:59 UTC, jeffreiffers approved these changes

2024-04-16 09:10 UTC, terjesyl approved these changes

2024-04-17 06:30 UTC, merged