fix(docs): updated catalog descriptions
Informasjonsforvaltning/fdk-frontend pull request #244
Opened 2024-09-24 13:27 UTC by Lillebo

2024-09-25 14:58 UTC, KurtStian commented on libs/dictionaries/src/lib/dictionaries/en/common.json
>                  "title": "Terms"
Concepts

2024-09-25 15:01 UTC, KurtStian commented on libs/dictionaries/src/lib/dictionaries/en/common.json
> +                "description": "Definitions of terms that the organization uses in its data",
"Definitions of concepts..."

2024-09-25 15:04 UTC, KurtStian commented on libs/dictionaries/src/lib/dictionaries/nb/common.json
> +                "description": "Tjenester som tilbys på vegne av offentlig sektor, og hendelser som kan utløse slike tjenester",
Skal vi si: "Tjenester som tilbys **av eller** på vegne av offentlig sektor,..."

2024-09-25 15:10 UTC, KurtStian commented on libs/dictionaries/src/lib/dictionaries/nn/common.json
> +                "description": "Tenester som blir tilbydde på vegner av offentleg sektor, og hendingar som kan utløyse slike tenester",
Vet ikke om det heter tilbydde eller tilbodne - eller om man kan si begge deler

Men skal vi si "...tilbydde av eller på vegner av..."

2024-09-25 15:17 UTC, KurtStian commented on libs/dictionaries/src/lib/dictionaries/en/common.json
> +                "description": "Services provided on behalf of the public sector and events that may trigger such services",
"Services provided by or on behalf of the public sector..." 
provided vs. offered ? Ser at jeg har brukt "offered" i ingressen til beskrivelsen til katalogen, men begge kan vel brukes.

2024-09-27 07:35 UTC, KjerstiSteien requested changes

2024-09-27 07:35 UTC, KjerstiSteien commented on libs/dictionaries/src/lib/dictionaries/en/common.json
> +                "description": "Services provided on behalf of the public sector and events that may trigger such services",
```suggestion
                "description": "Services provided by or on behalf of the public sector and events that may trigger such services",
```

2024-09-27 07:35 UTC, KjerstiSteien commented on libs/dictionaries/src/lib/dictionaries/en/common.json
> +                "description": "Definitions of terms that the organization uses in its data",
```suggestion
                "description": "Definitions of concepts that the organization uses in its data",
```

2024-09-27 07:35 UTC, KjerstiSteien commented on libs/dictionaries/src/lib/dictionaries/nb/common.json
> +                "description": "Tjenester som tilbys på vegne av offentlig sektor, og hendelser som kan utløse slike tjenester",
```suggestion
                "description": "Tjenester som tilbys av eller på vegne av offentlig sektor, og hendelser som kan utløse slike tjenester",
```

2024-09-27 13:29 UTC, KjerstiSteien approved these changes

2024-09-27 13:29 UTC, merged