test(data-hunter): add e2e
Informasjonsforvaltning/fdk-frontend pull request #72
Opened 2024-05-23 07:58 UTC by pooriamehregan

2024-05-27 12:34 UTC, Lillebo requested changes

2024-05-27 12:34 UTC, Lillebo commented on apps/forms-e2e/src/data-hunter/utils/helpers.ts
> +    'wcag2aaa',
Jeg har allerede fjernet denne i #75, men kan nevne det her også: WCAG AAA er ikke lovpålagt, så denne kan fjernes :)

```suggestion
```

2024-05-31 11:04 UTC, pooriamehregan commented on apps/forms-e2e/project.json
> +  }
Denne blir fikset i en commit som innfører automatisk sortering av json filer: https://github.com/Informasjonsforvaltning/fdk-frontend/pull/79/commits/75c9c2180853b1e22b4533c1e812a8bd1c416420

2024-05-31 11:05 UTC, pooriamehregan commented on apps/forms-e2e/src/data-hunter/page-object-model/formPage.ts
> +    await this.submitButton().click();
Har gjort dette i en nyere commit:
https://github.com/Informasjonsforvaltning/fdk-frontend/pull/79/commits/9305039dd87f613240c5aa53c741a75061d1cccb

2024-06-04 06:33 UTC, jeffreiffers approved these changes

2024-06-06 16:31 UTC, merged